apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ $.Release.Namespace | default "default" | quote }}
data:
  # Edge env variables
  nats: {{ ( printf "nats://%s-nats.default.svc.cluster.local:4222" .Release.Name ) | quote }}
  service: ""
  config.json: |-
    {
      "key1": "value1",
      "key2": "value2"
    }